batch_size: 256
epochs: 80
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 50
weight_decay: 10e-6
fp16_precision: False
allow_multi_gpu: True

model:
  out_dim: 256
  base_model: "resnet18"

dataset:
  data: "msi"
  s: 1
  input_shape: (224,224,3)
  num_workers: 0
  valid_size: 0.05
  path_to_msi_data: "/home/yonis/histogenomics-msc-2019/yoni-code/MsiPrediction/data/msidata/crc_dx/train/"


loss:
  temperature: 0.5
  use_cosine_similarity: True
